FROM node:20.11.0-alpine AS base

COPY . /app
WORKDIR /app

FROM base AS build
RUN --mount=type=cache,id=npm,target=/npm/store npm install --lockfile-only
RUN npm run build:rspack

FROM base
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/rspack-dist /app/rspack-dist

EXPOSE 8000
CMD [ "npm", "run", "dev:webpack" ]
