FROM node:20.11.0-alpine AS base
COPY . /app
WORKDIR /app

FROM base AS deps
RUN --mount=type=cache,id=npm,target=/npm/store \
    npm ci --omit=dev

FROM base AS build
RUN --mount=type=cache,id=npm,target=/npm/store \
    npm ci
RUN npm run build:rspack

FROM base
COPY --from=deps /app/node_modules /app/node_modules
COPY --from=build /app/rspack-dist /app/rspack-dist

EXPOSE 8000
CMD [ "npm", "run", "dev:rspack" ]
